config:
    run_type: "tune"
    metric: "Sharpe"
    model_name: "all"
    data_path: "/data"
    results_path: "/results"
envs:
    StockTrading:
        hmax: 2
        initial_amount: 10
        buy_cost_pc: 0.01
        sell_cost_pc: 0.01
        reward_scaling: 1
        max_short: 2
        reset_days: 0
        print_verbosity: 0
    PortfolioAllocation:
models:
    ddpg:
        train:
            iters: 20
            train_cycle: 1
            batch_size: 64
            buffer_size: 50000
            hidden_p: 128
            hidden_q: 128
            lr_p: 0.001
            lr_q: 0.001
            gamma: 0.98
            tau: 0.05
            k: 0.05
            decay_val: 0.1
            act_noise: 0.1
            expl_factor: 0.2
        tune:
            hidden_p:
                - 64
                - 128
                - 256
            hidden_q:
                - 64
                - 128
                - 256
            lr_p:
                min: 0.0001
                max: 0.001
            lr_q:
                min: 0.0001
                max: 0.001
            gamma:
                min: 0.9
                max: 0.99
            tau:
                min: 0.01
                max: 0.1
            act_noise:
                min: 0.01
                max: 0.1
            iters:
                min: 10
                max: 100
            train_cycle:
                min: 1
                max: 10

    ddqn:
        train:
            iters: 20
            train_cycle: 1
            batch_size: 64
            buffer_size: 50000
            hidden_size: 128
            lr: 0.001
            gamma: 0.98
            tau: 0.05
            k: 0.05
            eps: 0.1
        tune:
            hidden_size:
                - 64
                - 128
                - 256
            lr:
                min: 0.0001
                max: 0.001
            gamma:
                min: 0.9
                max: 0.99
            tau:
                min: 0.01
                max: 0.1
            eps:
                min: 0.01
                max: 0.1
            iters:
                min: 10
                max: 100
            train_cycle:
                min: 1
                max: 10
